version:2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@mucadoo/wiki-geo-data"
    groups:
      wiki-geo-updates:
        patterns:
          - "@mucadoo/*"
