export const ALIASES: Record<string, string[]> = {
  // Region Aliases
  "washington dc": ["dc", "district of columbia"],
  "czechia": ["czech republic"],
  "united kingdom": ["uk", "great britain"],
  // Capital Aliases
  "saint paul": ["st paul"],
  "kyiv": ["kiev"],
  "djibouti city": ["djibouti"],
  "mbabane": ["lobamba"],
  "pretoria": ["cape town", "bloemfontein"],
  "dodoma": ["dar es salaam"],
  "laayoune": ["el aaiun"],
  "colombo": ["sri jayawardenepura kotte", "kotte"],
  "naypyidaw": ["yangon", "rangoon"],
  "sanaa": ["aden", "sana'a"],
  "kuwait city": ["kuwait"],
  // World country aliases (abbreviated/alternate topology names -> natural guesses)
  "antigua and barb": ["antigua and barbuda"],
  "bosnia and herz": ["bosnia and herzegovina"],
  "central african rep": ["central african republic"],
  "cote d'ivoire": ["ivory coast"],
  "dem rep congo": ["democratic republic of the congo", "dr congo", "drc", "congo kinshasa"],
  "congo": ["republic of the congo", "congo brazzaville"],
  "dominican rep": ["dominican republic"],
  "eq guinea": ["equatorial guinea"],
  "eswatini": ["swaziland"],
  "macedonia": ["north macedonia"],
  "marshall is": ["marshall islands"],
  "s sudan": ["south sudan"],
  "solomon is": ["solomon islands"],
  "st kitts and nevis": ["saint kitts and nevis"],
  "st vin and gren": ["saint vincent and the grenadines", "st vincent and the grenadines"],
  "united states of america": ["united states", "usa", "us", "america"],
  "w sahara": ["western sahara"],
  "timorleste": ["timor leste", "east timor"],
  "guineabissau": ["guinea bissau"],
  "myanmar": ["burma"],
  "russia": ["russian federation"],
  "vatican": ["vatican city"],
  "micronesia": ["federated states of micronesia", "fsm"],
  "cabo verde": ["cape verde"],
  "bahamas": ["the bahamas"],
  "gambia": ["the gambia"],
  "netherlands": ["holland"],
  "palestine": ["state of palestine", "palestinian territories"],
  "turkey": ["turkiye"],
  "sao tome and principe": ["sao tome"],
};
